version: '3'

services:
  odiyaan:
    build:
      context: .
      args:
        NGROK_TOKEN: ${NGROK_TOKEN}
    ports:
      - "80:80"
      - "8888:8888"
      - "8080:8080"
      - "443:443"
      - "5130:5130"
      - "5131:5131"
      - "5132:5132"
      - "5133:5133"
      - "5134:5134"
      - "5135:5135"
      - "3306:3306"
    stdin_open: true
    tty: true
