
on:
  push:
    branches:
      - main

jobs:
  deploy-to-compose-deploy:
    runs-on: ubuntu-latest
    name: ComposeDeploy
    steps:
      - uses: actions/checkout@v4
      - id: ComposeDeploy
        uses: lukasvdberk/compose-deploy-action@master
        env:
          API_KEY: ${{ secrets.COMPOSE_DEPLOY_API_KEY }}
        with:
          project-id: '794864411'
          docker-compose-file: ''
    