name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          # Use NGROK_TOKEN environment variable in your build or deployment process
          echo "Using NGROK_TOKEN: $NGROK_TOKEN"
